services:
  web:
    build: .
    container_name: ptb_fastapi
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: ptb_celery_worker
    command: celery -A services.celery_worker.celery_app worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started

  redis:
    image: redis:7
    container_name: ptb_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
